# Generated by Django 2.1.2 on 2019-09-02 02:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='学号')),
                ('Student_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('Student_department', models.SmallIntegerField(choices=[(0, '技术开发部'), (1, '秘书部'), (2, '编辑部'), (3, '管理部'), (4, '部门5'), (5, '部门6'), (6, '部门7'), (7, '部门8')], default=0, verbose_name='部门')),
                ('Student_position', models.SmallIntegerField(choices=[(0, '总队'), (1, '副总队'), (2, '部长'), (3, '副部长'), (4, '队员')], default=0, verbose_name='职位')),
            ],
            options={
                'db_table': 'student_test',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_week', models.SmallIntegerField(default=1, verbose_name='第几周')),
                ('work_times', models.FloatField(default=0.0, verbose_name='工作时长')),
                ('work_details', tinymce.models.HTMLField(verbose_name='工作详情')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
            options={
                'db_table': 'worktime_test',
            },
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('work', 'which_week')},
        ),
    ]
