# Generated by Django 2.1.2 on 2019-09-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_is_activate',
            field=models.SmallIntegerField(default=0, verbose_name='是否审核通过'),
        ),
    ]
